# Generated by Django 4.2 on 2023-05-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_director_review_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.UUIDField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
